---
# configurations for github actions

name: Checks

on: [push]

#runs on: runner - github has multiple os to run the jobs on. docker compose is preinstalled on this version for example.docker compose up
#uses: defines what action it is - docker login action.
# checkout action - checks out code, by default doesn't checks out
jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-20.04
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run: docker compose run --rm app sh -c "python manage.py test"
      - name: Lint
        run: docker compose run --rm app sh -c "flake8"